# Site settings
title: 默然
SEOTitle: 默然的博客 | 默然
header-img: img/home-bg-evening.jpg
email: buzaijianghua@gmail.com
description: "世事悠悠，不如山丘。青松蔽日，碧涧长秋。山云当幕，夜月为钩。卧藤萝下，块石枕头。不朝天子，岂羡王侯。生死无虑，更复何忧。"
keyword: "默然, Stop Talking, stoptalking, 真费劲, @stoptalking, 默然的博客, Stop Talking Blog, 博客, 个人网站, 互联网, 前端, 设计, 产品, 肖玉的男朋友"
baseurl: "/stoptalking" # the subpath of your site, e.g. /blog
url: "/stoptalking/" # the base hostname & protocol for your site
assetsurl:  "/stoptalking/assets/"                         # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: true
#weibo_username:     seannell
#zhihu_username:     seannell
#github_username:    seannell
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: seannell
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "兀然无事坐，春来草自青"
sidebar-avatar: img/avatar-suitsman.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "默然",
        href: "http://seannell.github.io/stoptalking"
    }
]
